export enum UserSessionState {
  CREATE_ACCOUNT = "create_account",
  MAIN_MENU = "main_menu",
  ONBOARD_MENU = "onboard_menu",
  CREATE_PASSWORD = "create_password",
  VERIFY_OTP = "verify_otp",
  LOGIN = "login",
  SEARCH_JOBS = "search_jobs",
  FOUND_JOBS_MENU = "found_jobs_menu",
  USER_PROFILE = "user_profile",
  SEND_CREDITS = "send_credits",
  GIGS_MENU = "gigs_menu",
  SIDE_GIG_STEP1_TITLE = "side_gig_step1_title",
  SIDE_GIG_STEP2_DESCRIPTION = "side_gig_step2_description",
  SIDE_GIG_STEP3_BUDGET = "side_gig_step3_budget",
  SIDE_GIG_STEP4_LOCATION = "side_gig_step4_location",
  SIDE_GIG_STEP5_REVIEW = "side_gig_step5_review",
  SIDE_GIG_STEP6_DEPOSIT = "side_gig_step6_deposit",
}
